# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'Reciplease' do

  pod 'Alamofire', '5.2'
  pod 'Kingfisher', '5.15'

  target 'RecipleaseTests' do
    inherit! :search_paths

    # Pods for testing

  end

end
